- name: check data directory
  command: test -x /var/lib/pgsql/11
  register: pg_data_exists
  ignore_errors: yes
- name: dnf | add repo
  dnf: name=https://download.postgresql.org/pub/repos/yum/11/fedora/fedora-{{ os_version }}-x86_64/pgdg-fedora11-11-2.noarch.rpm
- name: dnf | install
  dnf:
    name:
      - postgresql11
      - postgresql11-libs
      - postgresql11-server
      - postgresql11-devel
      - postgresql11-contrib
      - python-psycopg2
    state: latest
- name: setup data directory
  shell: /usr/pgsql-11/bin/postgresql-11-setup initdb
  when: pg_data_exists is failed
- name: local ipv4 md5 connection
  replace: "dest=/var/lib/pgsql/11/data/pg_hba.conf regexp='127.0.0.1/32            ident' replace='127.0.0.1/32            md5'"
- name: local ipv6 md5 connection
  replace: "dest=/var/lib/pgsql/11/data/pg_hba.conf regexp='::1/128                 ident' replace='::1/128                 md5'"
- name: restart
  service: name=postgresql-11 state=restarted enabled=true
- name: set current user as superuser
  become: true
  become_user: postgres
  postgresql_user: 'name={{dev_user}} state=present role_attr_flags=SUPERUSER,CREATEROLE,CREATEDB,INHERIT,LOGIN,REPLICATION'
- name: create db for current user
  become: true
  become_user: postgres
  postgresql_db: 'name={{dev_user}}'
