- name: check installed
  command: test -x /usr/pgsql-9.5
  register: pg_installed
  ignore_errors: yes
- name: dnf | exclude old repos
  ini_file: 'dest=/etc/yum.repos.d/CentOS-Base.repo section="{{item}}" option="exclude" value="postgresql*"'
  with_items:
    - base
    - updates
- name: dnf | add repo
  dnf: 'name=http://yum.postgresql.org/9.5/fedora/fedora-23-x86_64/pgdg-fedora95-9.5-3.noarch.rpm state=present'
- name: dnf | install
  dnf: name="{{item}}" state=latest
  with_items:
    - postgresql95
    - postgresql95-libs
    - postgresql95-server
    - postgresql95-devel
    - postgresql95-contrib
    - python-psycopg2
- name: local ipv4 md5 connection
  replace: "dest=/var/lib/pgsql/9.5/data/pg_hba.conf regexp='127.0.0.1/32            ident' replace='127.0.0.1/32            md5'"
- name: local ipv6 md5 connection
  replace: "dest=/var/lib/pgsql/9.5/data/pg_hba.conf regexp='::1/128                 ident' replace='::1/128                 md5'"
- name: restart
  service: name=postgresql-9.5 state=restarted enabled=true
- name: set current user as superuser
  become_user: postgres
  postgresql_user: name={{lookup('env', 'USER')}} state=present role_attr_flags=SUPERUSER,CREATEROLE,CREATEDB,INHERIT,LOGIN,REPLICATION
- name: create db for current user
  become_user: postgres
  postgresql_db: name={{lookup('env', 'USER')}}
- name: path to pg bin
  become: false
  lineinfile: "dest={{lookup('env', 'HOME')}}/.bashrc line='export PATH=$PATH:/usr/pgsql-9.5/bin/' insertafter='EOF' state=present"
