- name: check data directory
  command: test -x /var/lib/pgsql
  register: pg_data_exists
  ignore_errors: yes
- name: dnf | install
  dnf: name={{item}} state=latest
  with_items:
    - postgresql
    - postgresql-libs
    - postgresql-server
    - postgresql-devel
    - postgresql-contrib
    - python-psycopg2
- name: setup data directory
  shell: postgresql-setup initdb
  when: pg_data_exists|failed
- name: local ipv4 md5 connection
  replace: "dest=/var/lib/pgsql/data/pg_hba.conf regexp='127.0.0.1/32            ident' replace='127.0.0.1/32            md5'"
- name: local ipv6 md5 connection
  replace: "dest=/var/lib/pgsql/data/pg_hba.conf regexp='::1/128                 ident' replace='::1/128                 md5'"
- name: restart
  service: name=postgresql state=restarted enabled=true
- name: set current user as superuser
  become: true
  become_user: postgres
  postgresql_user: 'name={{dev_user}} state=present role_attr_flags=SUPERUSER,CREATEROLE,CREATEDB,INHERIT,LOGIN,REPLICATION'
- name: create db for current user
  become: true
  become_user: postgres
  postgresql_db: 'name={{dev_user}}'
