---
- hosts: localhost
  roles:
    # - { role: system_common, become: true }
    # - { role: mysql, become: true }
    - { role: postgresql, become: true, tags: pg }
    - { role: nvim, become: true, tags: nvim }
    - { role: nodejs, become: true }
    # - rbenv
