- hosts: all
  become: true
  become_user: root
  roles:
    - { role: system_common, tags: system }
    - { role: redis, tags: redis }
    - { role: nodejs, tags: node }
    - { role: postgresql, tags: pg }
    - { role: docker, tags: docker }
    - { role: rabbitmq, tags: mq }

- hosts: all
  become: true
  become_user: '{{ dev_user }}'
  roles:
    - { role: rbenv, tags: ruby }
