- hosts: all
  become: true
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/env python3
  roles:
    - { role: system_common, tags: system }
    - { role: docker, tags: docker }

- hosts: all
  become: true
  become_user: '{{ user }}'
  vars:
    ansible_python_interpreter: /usr/bin/env python3
  roles:
    - { role: rbenv, tags: ruby }
    - { role: node, tags: node }
