---
- hosts: localhost
  become: true
  roles:
    - { role: system_common }
    - { role: mysql, tags: mysql }
    - { role: postgresql, tags: pg }
    - { role: redis, tags: redis }
    - { role: nvim, tags: nvim }
    - { role: nodejs }

- hosts: localhost
  roles:
    - rbenv
