# Создание аккаунтов пользователей, копирование необходимых ключей.
- name: 'account | create dvps_user'
  user: 'name={{dvps_user}} shell=/bin/bash groups=wheel'
- name: 'account | add authorized_keys to dvps_user'
  authorized_key: user={{dvps_user}} key='{{lookup("file", "keys/" + item + ".pub")}}'
  with_items: '{{developers}}'
- name: 'account | create apps_user'
  user: 'name={{apps_user}} shell=/bin/bash generate_ssh_key=yes'
- name: 'account | add authorized_keys to apps user'
  authorized_key: user={{apps_user}} key='{{lookup("file", "keys/" + item + ".pub")}}'
  with_items: '{{developers}}'
- name: 'account | create developers accounts'
  user: 'name={{item}} shell=/bin/bash groups=apps,wheel'
  with_items: '{{developers}}'
- name: 'account | add authorized_keys to developers'
  authorized_key: user={{item}} key='{{lookup("file", "keys/" + item + ".pub")}}'
  with_items: '{{developers}}'

# Настройки sudo
- name: 'sudo | nopassword for wheel'
  lineinfile: "dest=/etc/sudoers state=present regexp='^%wheel' line='%wheel ALL=(ALL) NOPASSWD: ALL'"

# Настройки ssh
- name: 'ssh | prevent root login'
  replace: "dest=/etc/ssh/sshd_config regexp='^#PermitRootLogin yes$' replace='PermitRootLogin no'"
- name: 'ssh | disable password authentication'
  replace: "dest=/etc/ssh/sshd_config regexp='^PasswordAuthentication yes$' replace='PasswordAuthentication no'"
