- name: install erlang
  dnf: name=erlang state=latest
- name: add rabbitmq rpm key
  rpm_key:
    state: present
    key: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
- name: repo file
  copy: src=rabbitmq.repo dest=/etc/yum.repos.d/rabbitmq.repo
- name: install
  dnf:
    name: rabbitmq-server-3.7.14-1.el7.noarch
    state: latest
- name: install rabbitmqadmin
  get_url:
    url: https://raw.githubusercontent.com/rabbitmq/rabbitmq-management/v3.7.14/bin/rabbitmqadmin
    dest: /usr/local/bin/rabbitmqadmin
    mode: 0655
- name: restart
  action: service name=rabbitmq-server state=restarted enabled=true
- name: enable management console
  shell: rabbitmq-plugins enable rabbitmq_management
