- name: check mysql installed
  command: test -x /usr/bin/mysql
  register: mysql_installed
  ignore_errors: yes
- name: dnf | install
  dnf: name={{item}} state=latest
  with_items:
    - mariadb
    - mariadb-server
    - mariadb-devel
    - MySQL-python
  when: mysql_installed|failed
- name: start service
  service: name=mariadb state=started
  when: mysql_installed|failed
- name: update root password
  become_user: mysql
  mysql_user: 'login_user=root login_password="" name=root host=localhost password=root priv=*.*:ALL,GRANT'
  when: mysql_installed|failed
- name: remove test datbase
  become_user: mysql
  mysql_db: db=test state=absent
  when: mysql_installed|failed
- name: restart mysql
  service: name=mariadb state=restarted enabled=yes
  when: mysql_installed|failed
