---

- name: install nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
    warn: false

- name: install lts
  shell: >
    . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install --lts
- name: install yarn
  shell: >
    . {{ ansible_env.HOME }}/.nvm/nvm.sh && npm install --global yarn