- name: dnf | install
  dnf: name={{item}} state=latest
  with_items:
    - docker
    - docker-compose
- name: add docker group
  group: name=docker state=present
- name: add {{dev_user}} to docker group
  user: name={{dev_user}} groups=docker append=true
- name: restart
  service: name=docker state=restarted enabled=true
