- name: install
  dnf:
    name:
      - moby-engine
      - docker-compose
    state: latest
- name: start
  service: name=docker state=restarted enabled=true
- name: Ensure group "docker" exists
  group:
    name: docker
    state: present
- name: Append user to "docker" group
  user:
    name: '{{ user }}'
    groups: docker
    append: yes
