- name: install
  dnf:
    name:
      - moby-engine
      - docker-compose
    state: latest
- name: start
  service: name=docker state=restarted enabled=true
# - name: install docker-machine
#   get_url:
#     url: https://github.com/docker/machine/releases/download/v0.16.1/docker-machine-Linux-x86_64
#     dest: /usr/local/bin/docker-machine
#     mode: 0755
#     force: yes
# - name: install docker-compose
#   get_url:
#     url: https://github.com/docker/compose/releases/download/1.23.2/docker-compose-Linux-x86_64
#     dest: /usr/local/bin/docker-compose
#     mode: 0755
#     force: yes
- name: Ensure group "docker" exists
  group:
    name: docker
    state: present
- name: Append user to "docker" group
  user:
    name: '{{ dev_user }}'
    groups: docker
    append: yes
