- name: update packages
  dnf: name=* state=latest
- name: install the 'Development tools' package group
  dnf: name="@Development tools" state=present
- name: install plugins core
  dnf: name=dnf-plugins-core state=latest
- name: get Fedora version
  command: rpm -E %fedora
  register: fedora_version
  args:
    warn: false
- name: install rpmfusion
  dnf:
    name:
      - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ os_version }}.noarch.rpm"
      - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ os_version }}.noarch.rpm"
    state: latest
- name: install dependencies
  dnf:
    name:
      - ImageMagick
      - biosdevname
      - busybox
      - bzip2
      - cowsay
      - ctags
      - discount
      - fedora-packager
      - fortune-mod
      - fuse-exfat
      - gcc-c++
      - git
      - htop
      - iftop
      - iotop
      - java-1.8.0-openjdk-devel
      - kernel-devel
      - libcurl
      - libcurl-devel
      - libffi-devel
      - libtool
      - libyaml-devel
      - lsof
      - nmap
      - openssl-devel
      - p7zip
      - p7zip-plugins
      - pv
      - readline
      - readline-devel
      - sqlite
      - sqlite-devel
      - strace
      - sysstat
      - the_silver_searcher
      - tmux
      - unzip
      - vim
      - vim-X11
      - zip
      - zlib
      - zlib-devel
      - zsh
      - fzf
      - ripgrep
      - libatomic
      - libXScrnSaver
      - xclip
    state: latest
- name: install tmuxp
  pip:
    name: tmuxp
    state: latest
- name: Set max_max_user_watches
  sysctl:
    name: fs.inotify.max_user_watches
    value: 524288
    state: present
    reload: yes
